#　ベースイメージとして公式のMySqlイメージを使用

FROM mysql:latest 

#環境変数を設定
ENV MYSQL_ROOT_PASSWORD=root_pw 
ENV MYSQL_DATABASE=team_1
ENV MYSQL_USER=team_1_user
ENV MYSQL_PASSWORD=team_1_pw
ENV TZ=Asia/Tokyo

#ポート3306を公開
EXPOSE 3306

