version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports: 
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo 
      TZ: "Asia/Tokyo"

    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf 
    
  webrick:
    build: ./webrick
    container_name: webrick-container
    ports:
      - "./webrick:/usr/src/app"
      command: ruby /usr/src/app/server.rb 
      
